version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - zip -r bundle.zip dist/*
artifacts:
  files:
    - "**/*"
  base-directory: dist
  name: bundle-$(date +%s)
