version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
      - chmod a+x build.sh
  build:
    commands:
      - npm run build
artifacts:
  files:
    - "**/*"
  base-directory: dist
  name: bundle-$(date +%s)
